const mongoose = require('mongoose');

const postSchema = new mongoose.Schema({
    athleteId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'User', 
        required: true 
    },
    videoUrl: { 
        type: String, 
        required: true 
    },
    // The Magic AI Payload
    aiMetrics: {
        type: mongoose.Schema.Types.Mixed, // Allows us to store flexible JSON objects
        default: {} 
        // Example expected payload: { footwork_score: 8, timing_score: 9, bat_speed: "80kmph" }
    },
    scoutSummary: {
        type: String // Max 20 words generated by Gemini
    }
}, {    
    timestamps: true 
});

module.exports = mongoose.model('Post', postSchema);